export * from "./types.js";
export * from "./registry.js";
export * from "./fs.js";
export * from "./shell.js";
export * from "./search.js";
export * from "./web.js";
export * from "./browser.js";
export * from "./code.js";
export * from "./interaction.js";
export * from "./memory-tools.js";
export * from "./task-tools.js";
export * from "./regex.js";
export * from "./task-bucket.js";
export * from "./codebase.js";
export * from "./str-replace.js";
export * from "./browser-automation.js";
export * from "./web-enhanced.js";
export * from "./coding-advanced.js";

import { registerFsTools } from "./fs.js";
import { registerShellTools } from "./shell.js";
import { registerSearchTools } from "./search.js";
import { registerWebTools } from "./web.js";
import { registerBrowserTools } from "./browser.js";
import { registerCodeTools } from "./code.js";
import { registerInteractionTools } from "./interaction.js";
import { registerMemoryTools } from "./memory-tools.js";
import { registerTaskTools } from "./task-tools.js";
import { registerRegexTools } from "./regex.js";
import { registerTaskBucketTools } from "./task-bucket.js";
import { registerCodebaseTools } from "./codebase.js";
import { registerStrReplaceTools } from "./str-replace.js";
import { registerBrowserAutomationTools } from "./browser-automation.js";
import { registerWebEnhancedTools } from "./web-enhanced.js";
import { registerCodingAdvancedTools } from "./coding-advanced.js";

export function registerAllTools() {
  registerFsTools();
  registerShellTools();
  registerSearchTools();
  registerWebTools();
  registerBrowserTools();
  registerCodeTools();
  registerInteractionTools();
  registerMemoryTools();
  registerTaskTools();
  registerRegexTools();
  registerTaskBucketTools();
  registerCodebaseTools();
  registerStrReplaceTools();
  registerBrowserAutomationTools();
  registerWebEnhancedTools();
  registerCodingAdvancedTools();
}
